# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql2
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
_default: &mysql
  adapter: mysql2
  host: localhost
  port: 3306
  encoding: utf8
  username: root

development:
  <<: *mysql
  database: myraces_development

# Warning: The database defined as "test" will be erased and
# Do not set this db to the same as development or production.
test: &test
  <<: *mysql
  database: myraces_test

production:
  <<: *mysql
  database: myraces

cucumber:
  <<: *test

